#!/bin/bash
# Installation Summary / Резюме на инсталацията

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              РЕЗЮМЕ НА ИНСТАЛАЦИЯТА                         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "🎉 Поздравления! Вашият Ubuntu сървър с Coolify е готов!"
echo ""
echo "📋 КАКВО Е ИНСТАЛИРАНО:"
echo "   ✅ Ubuntu Server с български език"
echo "   ✅ RAID1 с 2x NVMe дискове"
echo "   ✅ Backup система с HDD"
echo "   ✅ Docker и Docker Compose"
echo "   ✅ Coolify за управление на приложения"
echo "   ✅ Автоматични backups всяка събота в 15:00"
echo "   ✅ Ежедневни health checks в 02:00"
echo "   ✅ Мониторинг и алармиране"
echo "   ✅ Сигурност (UFW, Fail2ban)"
echo ""
echo "🔗 ДОСТЪП:"
echo "   Coolify Web UI: http://$(hostname -I | awk '{print $1}'):8000"
echo "   SSH: ssh $(whoami)@$(hostname -I | awk '{print $1}')"
echo ""
echo "📁 ВАЖНИ ДИРЕКТОРИИ:"
echo "   /data/           - RAID1 данни"
echo "   /mnt/backup/     - Backup дискове"
echo "   /data/coolify/   - Coolify данни"
echo ""
echo "⚡ БЪРЗИ КОМАНДИ:"
echo "   dashboard        - Статус на сървъра"
echo "   backup          - Ръчно backup"
echo "   raidstatus      - RAID статус"
echo "   quick-commands.sh - Пълна справка"
echo ""
echo "📚 ДОКУМЕНТАЦИЯ:"
echo "   /mnt/backup/recovery-docs/ - Ръководства за възстановяване"
echo ""
echo "🔔 ВАЖНО:"
echo "   1. Сменете default паролите в Coolify"
echo "   2. Настройте домейн и SSL сертификат"
echo "   3. Тествайте backup системата"
echo "   4. Мониторирайте RAID статуса редовно"
echo ""
echo "🆘 ПРИ ПРОБЛЕМИ:"
echo "   verify-setup.sh  - Проверка на настройката"
echo "   system-info.sh   - Системна информация"
echo "   Логове: /var/log/"
echo ""
echo "Успех с вашия нов сървър! 🚀"